apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: eGRxNDlhbG0=
  CLOUDINARY_KEY: NDQyNjc5MTgzNzU5NDc0
  CLOUDINARY_SECRET: TkQ5elduVnZMX0dJaklTcS1INk1vUGkwNi1v
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lkbVZ1YTJGMFlYTjFiVzRpTENKaElqb2lZMjF6WW0xemVtVTNNRGw1WlRKNGNYQm1ZVEZsY1daeVlpSjkuaFFqckNTUU0zaGk0Y0RqdzZWT2QxZw==
  DB_URL: bW9uZ29kYitzcnY6Ly9zdW1hbnRodmVua2F0YTI2X2RiX3VzZXI6PGRiX3Bhc3N3b3JkPkBjbHVzdGVyMC4xcjlrc2I5Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
