apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHB6YmdodXl5
  CLOUDINARY_KEY: NTYyMjM0MTc5MTc3NDI3
  CLOUDINARY_SECRET: bXRQQWc1aUdIX0FyVXhEZDVTZzlWUVRUTGZv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYVd0dGRYTjBZV1poTnpjaUxDSmhJam9pWTIxellUUjJPV3h1TUd0MFpqSjRjakl6ZUhGME56Rm5kU0o5LklPdzBLcHRUeHR4eEo4STBNcUN1bFE=
  DB_URL: bW9uZ29kYitzcnY6Ly9zdW1hbnRodmVua2F0YTI2X2RiX3VzZXI6PGRiX3Bhc3N3b3JkPkBjbHVz
dGVyMC4xcjlrc2I5Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
